global:
  scrape_interval: 1m
  
  scrape_timeout: 10s

  external_labels:
    monitor: 'aspire-monitor'

scrape_configs:
  - job_name: 'aquiles-api'
    scheme: https
    tls_config:
        insecure_skip_verify: true 
    static_configs:
      - targets:
          - 'host.docker.internal:7226' 

  - job_name: 'enderecos-api'
    scheme: https
    tls_config:
        insecure_skip_verify: true 
    static_configs:
      - targets:
          - 'host.docker.internal:7028' 