//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aquiles.Exception {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMensagensDeErro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMensagensDeErro() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aquiles.Exception.ResourceMensagensDeErro", typeof(ResourceMensagensDeErro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O bairro é obrigatório.
        /// </summary>
        public static string BAIRRO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("BAIRRO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O cep é obrigatório.
        /// </summary>
        public static string CEP_OBRIGATORIO {
            get {
                return ResourceManager.GetString("CEP_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CNPJ informado é inválido.
        /// </summary>
        public static string CNPJ_INVALIDO {
            get {
                return ResourceManager.GetString("CNPJ_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo CPFCNPJ não pode ter menos que 11 e nem mais que 14 números.
        /// </summary>
        public static string CNPJCPF_TAMANHO_INVALIDO {
            get {
                return ResourceManager.GetString("CNPJCPF_TAMANHO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O CPF informado é inválido.
        /// </summary>
        public static string CPF_INVALIDO {
            get {
                return ResourceManager.GetString("CPF_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A descrição deve ser informada.
        /// </summary>
        public static string DESCRICAO_OBRIGATORIA {
            get {
                return ResourceManager.GetString("DESCRICAO_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Email do usuário deve ser informado..
        /// </summary>
        public static string EMAIL_USUARIO_EMBRANCO {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Email do usuário é inválido..
        /// </summary>
        public static string EMAIL_USUARIO_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Usuário informado já esta cadastrado no banco de dados..
        /// </summary>
        public static string EMAIL_USUARIO_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("EMAIL_USUARIO_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O estado é obrigatório.
        /// </summary>
        public static string ESTADO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("ESTADO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de fim da vigência da fatura é obrigatória..
        /// </summary>
        public static string FATURA_FIM_VIGENCIA_OBRIGATORIA {
            get {
                return ResourceManager.GetString("FATURA_FIM_VIGENCIA_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de início da vigência da fatura é obrigatória..
        /// </summary>
        public static string FATURA_INICIO_VIGENCIA_OBRIGATORIA {
            get {
                return ResourceManager.GetString("FATURA_INICIO_VIGENCIA_OBRIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fatura não pode ser negativa.
        /// </summary>
        public static string FATURA_NEGATIVA {
            get {
                return ResourceManager.GetString("FATURA_NEGATIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data de vencimento da fatura não pode ser anterior à data atual..
        /// </summary>
        public static string FATURA_VENCIMENTO {
            get {
                return ResourceManager.GetString("FATURA_VENCIMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo identidade deverá conter somente números.
        /// </summary>
        public static string IDENTIDADE_CARACTERES_ESPECIAIS {
            get {
                return ResourceManager.GetString("IDENTIDADE_CARACTERES_ESPECIAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Identidade deverá ter no mínimo 6 e no máximo 20 números.
        /// </summary>
        public static string IDENTIDADE_TAMANHO_INVALIDO {
            get {
                return ResourceManager.GetString("IDENTIDADE_TAMANHO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Parâmetros de login inválidos.
        /// </summary>
        public static string LOGIN_INVALIDO {
            get {
                return ResourceManager.GetString("LOGIN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O logradouro é obrigatório.
        /// </summary>
        public static string LOGRADOURO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("LOGRADOURO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O municipio é obrigatório.
        /// </summary>
        public static string MUNICIPIO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("MUNICIPIO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Nome do cliente deve ter no mínimo 3 e no máximo 45 caracteres.
        /// </summary>
        public static string NOME_CLIENTE_TAMANHO_INVALIDO {
            get {
                return ResourceManager.GetString("NOME_CLIENTE_TAMANHO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Nome do cliente deve ser informado.
        /// </summary>
        public static string NOME_CLIENTE_VAZIO {
            get {
                return ResourceManager.GetString("NOME_CLIENTE_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Nome fantasia não poderá conter caracteres especiais.
        /// </summary>
        public static string NOME_FANTASIA_CARACTERES_ESPECIAIS {
            get {
                return ResourceManager.GetString("NOME_FANTASIA_CARACTERES_ESPECIAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Nome fantasia deve ter no mínimo 3 e no máximo 45 caracteres.
        /// </summary>
        public static string NOME_FANTASIA_TAMANHO_INVALIDO {
            get {
                return ResourceManager.GetString("NOME_FANTASIA_TAMANHO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Nome do usuário deve ser informado..
        /// </summary>
        public static string NOME_USUARIO_EMBRANCO {
            get {
                return ResourceManager.GetString("NOME_USUARIO_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número é obrigatório.
        /// </summary>
        public static string NUMERO_OBRIGATORIO {
            get {
                return ResourceManager.GetString("NUMERO_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Órgão expedidor não poderá conter caracteres especiais.
        /// </summary>
        public static string ORGAO_EXPEDIDOR_CARACTERES_ESPECIAIS {
            get {
                return ResourceManager.GetString("ORGAO_EXPEDIDOR_CARACTERES_ESPECIAIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Órgao expedidor deverá ter no máximo 10 caracteres.
        /// </summary>
        public static string ORGAO_EXPEDIDOR_TAMANHO_INVALIDO {
            get {
                return ResourceManager.GetString("ORGAO_EXPEDIDOR_TAMANHO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quando informada identidade deverá ser informado o órgão expedidor.
        /// </summary>
        public static string ORGAO_EXPEDIDOR_VAZIO {
            get {
                return ResourceManager.GetString("ORGAO_EXPEDIDOR_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade de usuários não pode ser zero.
        /// </summary>
        public static string QUANTIDADE_USUARIO_NEGATIVO {
            get {
                return ResourceManager.GetString("QUANTIDADE_USUARIO_NEGATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha deve conter no mínimo seis caracteres.
        /// </summary>
        public static string SENHA_USUARIO_TAMANHO_INVALIDO {
            get {
                return ResourceManager.GetString("SENHA_USUARIO_TAMANHO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O status deve ser informado.
        /// </summary>
        public static string STATUS_OBRIGATORIO {
            get {
                return ResourceManager.GetString("STATUS_OBRIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O tipo de cliente deve ser informado corretamente.
        /// </summary>
        public static string TIPO_DEVE_SER_INFORMADO {
            get {
                return ResourceManager.GetString("TIPO_DEVE_SER_INFORMADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Realize o login novamente!.
        /// </summary>
        public static string TOKEN_EXPIRADO {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não tem permissão para acessar esse recurso.
        /// </summary>
        public static string USUARIO_SEM_PERMISSAO {
            get {
                return ResourceManager.GetString("USUARIO_SEM_PERMISSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor do plano não pode ser negativo.
        /// </summary>
        public static string VALOR_PLANO_NEGATIVO {
            get {
                return ResourceManager.GetString("VALOR_PLANO_NEGATIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vigencia do mês deve ser maior que zero.
        /// </summary>
        public static string VIGENCIA_MES_NEGATIVA {
            get {
                return ResourceManager.GetString("VIGENCIA_MES_NEGATIVA", resourceCulture);
            }
        }
    }
}
